# This workflow creates Godot 3.x with added third party modules

name: Image Linux

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      # See how this image is built at https://github.com/Flux159/godot-docker
      image: flux159/godot:1.0.0
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      with:
        repository: lawnjelly/godot
        ref: titan

    # get javascript module
    - uses: actions/checkout@v2
      with:
        repository: GodotExplorer/ECMAScript
        path: modules/ECMAScript/

    - name: Show folders before
      run: pwd && whoami && ls -R && ls misc

        
    # We should always be explicit with our flags usage here since it's gonna be sure to always set those flags
    - name: Compilation
      run: |
        scons -j2 verbose=no warnings=moderate werror=no platform=x11 tools=yes tests=no target=release_debug
        strip bin/godot.x11.opt.tools.64
        
    - name: Show folders after
      run: pwd && whoami && ls -R
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: godot-titan-linux-editor (x64)
        path: bin/godot.x11.opt.tools.64
